# -*- coding: utf-8 -*-
"""Copy of Final_codingPortion_CPSC222.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qYoN0ieoNI-kXo1lCkRgSPy7kidtPC6T
"""

## TASK SET 1 ##
addr_book = {'Smith':['509-444-2121','next door neighbor'],
             'Malek':['208-544-8686','room mate'],
             'Quresh':['570-751-2121', 'Cousin']}

print(addr_book['Smith'][0])
addr_book['Malek'][1] = 'Best Friend'
print(addr_book)

for name in addr_book:
  print(name, addr_book[name][0])
#Done

## TASK SET 2 ##
sales = [132849, 23487, 34829, 489247, 574872, 698374, 73498]
print(sales[4:])
print(sales[1:4])
sales.append(885434)
print(sales)
##Done

from ast import Num
## TASK SET 3 ##
def listinator(list1, list2, num):
  Tlist = list1 + list2
  Rlist = list1 * num
  Alist = list2 + [num]
  print(Tlist, Rlist, Alist)
  return (Tlist, Rlist, Alist)

pets = ['llama', 'fish', 'rat']
lockers = [23, 18, 77, 26]

list_results = listinator(pets, lockers, 4)
for results in list_results:
  print(results)
#Done

## TASK SET 4 ##
# 1.
for i in range( 6, 73, 3):
  print(i, end="*")

# 2.
for k in range(-200,200,1):
  print(k, end="/")
#Done

## TASK SET 5 ##
def singularize(name):
  if name[-1] == 's':
    print(name[:-1])
  else:
    print('not plural')

singularize("Apples")
singularize("mom's")
singularize("mess")
singularize("Christmas")
singularize("Present")
#Done